---
- hosts: tag_Type_boilkettle
  become: true
  become_method: sudo
  remote_user: ubuntu    
  gather_facts: false
  vars_files:
    - "{{ vaultfile }}"
  pre_tasks:
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - setup: # aka gather_facts
  roles:      
    - role: geerlingguy.java
    #- role: andrewrothstein.anaconda
      #anaconda_parent_dir: "/home/ubuntu"
    - role: boilkettle
      dbname: boilkettle
      dbuser: "{{ db_username }}"
      dbpassword: "{{ db_password }}"




